"""
Analytics V2
============

Descriptive, comparative, inventory and model-performance analytics
for the AI Demand & Inventory Optimizer.

Uses ONLY the project's sales_data.csv and generated V2 outputs.

Important:
- Category analytics assigns one category per Store×Product series
  using the latest historical observation.
- This prevents duplicate recommendation rows when category values
  vary across historical records.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any, Dict, Optional

import numpy as np
import pandas as pd


# ---------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------

ROOT_DIR = Path(__file__).resolve().parents[1]
DATA_PATH = ROOT_DIR / "sales_data.csv"
FORECAST_PATH = ROOT_DIR / "outputs" / "forecasts_v2.csv"
RECOMMENDATION_PATH = ROOT_DIR / "outputs" / "recommendations_v2.csv"
METADATA_PATH = ROOT_DIR / "models" / "model_metadata_v2.json"
ROLLING_VALIDATION_PATH = ROOT_DIR / "outputs" / "rolling_validation_v2.csv"
VALIDATION_PREDICTIONS_PATH = ROOT_DIR / "outputs" / "validation_predictions_v2.csv"


# ---------------------------------------------------------------------
# Data loading helpers
# ---------------------------------------------------------------------

def load_data(path: Optional[str | Path] = None) -> pd.DataFrame:
    """Load the historical sales dataset."""
    csv_path = Path(path) if path else DATA_PATH

    if not csv_path.exists():
        raise FileNotFoundError(
            f"Dataset not found: {csv_path}"
        )

    df = pd.read_csv(csv_path)

    if "Date" in df.columns:
        df["Date"] = pd.to_datetime(df["Date"])

    return df


def _ensure_data(
    data: Optional[pd.DataFrame] = None,
) -> pd.DataFrame:
    """Return a safe copy of the supplied or default dataset."""
    if data is None:
        return load_data()

    result = data.copy()

    if "Date" in result.columns:
        result["Date"] = pd.to_datetime(result["Date"])

    return result


def _load_recommendations() -> pd.DataFrame:
    """Load inventory recommendations generated by inventory.py."""
    if not RECOMMENDATION_PATH.exists():
        return pd.DataFrame()

    return pd.read_csv(RECOMMENDATION_PATH)


def _load_forecasts() -> pd.DataFrame:
    """Load generated V2 forecasts."""
    if not FORECAST_PATH.exists():
        return pd.DataFrame()

    df = pd.read_csv(FORECAST_PATH)

    if "Date" in df.columns:
        df["Date"] = pd.to_datetime(df["Date"])

    return df


# ---------------------------------------------------------------------
# Dataset overview
# ---------------------------------------------------------------------

def get_dataset_overview(
    data: Optional[pd.DataFrame] = None,
) -> Dict[str, Any]:
    """Return high-level dataset information."""

    df = _ensure_data(data)

    return {
        "rows": int(len(df)),
        "columns": int(len(df.columns)),
        "date_min": (
            df["Date"].min().strftime("%Y-%m-%d")
            if "Date" in df.columns and not df.empty
            else None
        ),
        "date_max": (
            df["Date"].max().strftime("%Y-%m-%d")
            if "Date" in df.columns and not df.empty
            else None
        ),
        "stores": int(df["Store ID"].nunique())
        if "Store ID" in df.columns else 0,
        "products": int(df["Product ID"].nunique())
        if "Product ID" in df.columns else 0,
        "categories": int(df["Category"].nunique())
        if "Category" in df.columns else 0,
        "regions": int(df["Region"].nunique())
        if "Region" in df.columns else 0,
        "weather_conditions": int(
            df["Weather Condition"].nunique()
        )
        if "Weather Condition" in df.columns else 0,
        "missing_values": int(df.isna().sum().sum()),
    }


# ---------------------------------------------------------------------
# Business summary
# ---------------------------------------------------------------------

def get_business_summary(
    data: Optional[pd.DataFrame] = None,
    recommendations: Optional[pd.DataFrame] = None,
) -> Dict[str, float]:
    """Return current inventory and forecast risk summary."""

    df = _ensure_data(data)

    if recommendations is None:
        recommendations = _load_recommendations()

    summary: Dict[str, float] = {
        "total_inventory": 0.0,
        "forecast_demand_p50": 0.0,
        "forecast_demand_p90": 0.0,
        "high_risk": 0,
        "medium_risk": 0,
        "low_risk": 0,
        "recommended_units": 0,
        "projected_shortage": 0.0,
        "average_daily_demand": 0.0,
        "stockout_risk_count": 0,
        "average_stockout_risk": 0.0,
    }

    if "Demand" in df.columns and not df.empty:
        summary["average_daily_demand"] = float(
            df["Demand"].mean()
        )

    if recommendations is None or recommendations.empty:
        return summary

    def col_sum(name: str) -> float:
        if name not in recommendations.columns:
            return 0.0
        return float(
            pd.to_numeric(
                recommendations[name],
                errors="coerce",
            ).fillna(0).sum()
        )

    summary["total_inventory"] = col_sum(
        "Current Inventory"
    )

    summary["forecast_demand_p50"] = col_sum(
        "Forecast P50 Demand"
    )

    summary["forecast_demand_p90"] = col_sum(
        "Forecast P90 Demand"
    )

    summary["recommended_units"] = int(
        round(col_sum("Recommended Order"))
    )

    summary["projected_shortage"] = col_sum(
        "Projected Shortage"
    )

    if "Risk Level" in recommendations.columns:
        risk = recommendations["Risk Level"].astype(str)

        summary["high_risk"] = int(
            (risk == "High").sum()
        )
        summary["medium_risk"] = int(
            (risk == "Medium").sum()
        )
        summary["low_risk"] = int(
            (risk == "Low").sum()
        )

    if "Stockout Risk" in recommendations.columns:
        stockout = pd.to_numeric(
            recommendations["Stockout Risk"],
            errors="coerce",
        )

        summary["stockout_risk_count"] = int(
            (stockout >= 70).sum()
        )

        summary["average_stockout_risk"] = float(
            stockout.mean()
        )

    return summary


# ---------------------------------------------------------------------
# Store analytics
# ---------------------------------------------------------------------

def get_store_analytics(
    data: Optional[pd.DataFrame] = None,
    recommendations: Optional[pd.DataFrame] = None,
) -> pd.DataFrame:
    """Return historical + forecast + inventory analytics by store."""

    df = _ensure_data(data)

    if recommendations is None:
        recommendations = _load_recommendations()

    historical = (
        df.groupby("Store ID")
        .agg(
            Historical_Demand=("Demand", "sum"),
            Average_Daily_Demand=("Demand", "mean"),
            Average_Inventory=("Inventory Level", "mean"),
            Latest_Inventory=("Inventory Level", "last"),
            Average_Price=("Price", "mean"),
            Average_Discount=("Discount", "mean"),
        )
        .reset_index()
    )

    if recommendations.empty:
        return historical

    numeric_columns = [
        "Current Inventory",
        "Forecast P50 Demand",
        "Forecast P90 Demand",
        "Recommended Order",
        "Projected Shortage",
        "Stockout Risk",
    ]

    for column in numeric_columns:
        if column in recommendations.columns:
            recommendations[column] = pd.to_numeric(
                recommendations[column],
                errors="coerce",
            )

    grouped = (
        recommendations.groupby("Store ID")
        .agg(
            Current_Inventory=("Current Inventory", "sum"),
            Forecast_P50_Demand=(
                "Forecast P50 Demand",
                "sum",
            ),
            Forecast_P90_Demand=(
                "Forecast P90 Demand",
                "sum",
            ),
            Recommended_Order=(
                "Recommended Order",
                "sum",
            ),
            Projected_Shortage=(
                "Projected Shortage",
                "sum",
            ),
            High_Risk=(
                "Risk Level",
                lambda x: int((x == "High").sum()),
            ),
            Medium_Risk=(
                "Risk Level",
                lambda x: int((x == "Medium").sum()),
            ),
            Low_Risk=(
                "Risk Level",
                lambda x: int((x == "Low").sum()),
            ),
            Average_Stockout_Risk=(
                "Stockout Risk",
                "mean",
            ),
        )
        .reset_index()
    )

    result = historical.merge(
        grouped,
        on="Store ID",
        how="left",
    )

    result["Forecast_to_Inventory_Ratio"] = (
        result["Forecast_P50_Demand"]
        / result["Current_Inventory"].replace(0, np.nan)
    )

    result["Inventory_Coverage_Days"] = (
        result["Current_Inventory"]
        / (
            result["Forecast_P50_Demand"] / 7
        ).replace(0, np.nan)
    )

    return result.sort_values(
        "Forecast_P50_Demand",
        ascending=False,
    ).reset_index(drop=True)


# ---------------------------------------------------------------------
# Product analytics
# ---------------------------------------------------------------------

def get_product_analytics(
    data: Optional[pd.DataFrame] = None,
    recommendations: Optional[pd.DataFrame] = None,
) -> pd.DataFrame:
    """Return historical + forecast + inventory analytics by product."""

    df = _ensure_data(data)

    if recommendations is None:
        recommendations = _load_recommendations()

    historical = (
        df.groupby("Product ID")
        .agg(
            Historical_Demand=("Demand", "sum"),
            Average_Daily_Demand=("Demand", "mean"),
            Average_Inventory=("Inventory Level", "mean"),
            Latest_Inventory=("Inventory Level", "last"),
            Average_Price=("Price", "mean"),
            Average_Discount=("Discount", "mean"),
        )
        .reset_index()
        .sort_values(
            "Historical_Demand",
            ascending=False,
        )
        .reset_index(drop=True)
    )

    historical["Demand_Rank"] = (
        historical.index + 1
    )

    if recommendations.empty:
        return historical

    grouped = (
        recommendations.groupby("Product ID")
        .agg(
            Current_Inventory=("Current Inventory", "sum"),
            Forecast_P50_Demand=(
                "Forecast P50 Demand",
                "sum",
            ),
            Forecast_P90_Demand=(
                "Forecast P90 Demand",
                "sum",
            ),
            Recommended_Order=(
                "Recommended Order",
                "sum",
            ),
            Projected_Shortage=(
                "Projected Shortage",
                "sum",
            ),
            High_Risk_Stores=(
                "Risk Level",
                lambda x: int((x == "High").sum()),
            ),
            Medium_Risk_Stores=(
                "Risk Level",
                lambda x: int((x == "Medium").sum()),
            ),
            Average_Stockout_Risk=(
                "Stockout Risk",
                "mean",
            ),
        )
        .reset_index()
    )

    result = historical.merge(
        grouped,
        on="Product ID",
        how="left",
    )

    result["Inventory_Coverage_Days"] = (
        result["Current_Inventory"]
        / (
            result["Forecast_P50_Demand"] / 7
        ).replace(0, np.nan)
    )

    return result


# ---------------------------------------------------------------------
# Category analytics - corrected
# ---------------------------------------------------------------------

def get_category_analytics(
    data: Optional[pd.DataFrame] = None,
    recommendations: Optional[pd.DataFrame] = None,
) -> pd.DataFrame:
    """
    Category-level demand and inventory analysis.

    IMPORTANT:
    Category is assigned at the Store×Product level using the
    latest observed historical category.

    This prevents recommendation rows from being duplicated when
    a Product ID has appeared under more than one category.
    """

    df = _ensure_data(data)

    if recommendations is None:
        recommendations = _load_recommendations()

    # Historical category metrics.
    historical = (
        df.groupby("Category")
        .agg(
            Historical_Demand=("Demand", "sum"),
            Average_Demand=("Demand", "mean"),
            Average_Inventory=(
                "Inventory Level",
                "mean",
            ),
            Average_Price=("Price", "mean"),
            Average_Discount=("Discount", "mean"),
        )
        .reset_index()
    )

    if recommendations is None or recommendations.empty:
        return historical

    # --------------------------------------------------------------
    # CRITICAL FIX:
    # Determine exactly ONE category for each Store×Product series.
    # The latest historical record represents the current mapping.
    # --------------------------------------------------------------

    latest_series = (
        df.sort_values("Date")
        .groupby(
            ["Store ID", "Product ID"],
            as_index=False,
        )
        .tail(1)
        [
            [
                "Store ID",
                "Product ID",
                "Category",
            ]
        ]
        .copy()
    )

    # Remove an existing Category column before merge.
    # Otherwise pandas creates Category_x / Category_y.
    rec = recommendations.drop(
        columns=["Category"],
        errors="ignore",
    ).copy()

    rec = rec.merge(
        latest_series,
        on=["Store ID", "Product ID"],
        how="left",
    )

    # Fail loudly if a recommendation cannot be categorized.
    if rec["Category"].isna().any():
        missing_count = int(
            rec["Category"].isna().sum()
        )
        raise ValueError(
            "Category mapping failed for "
            f"{missing_count} recommendation rows."
        )

    # Numeric safety.
    numeric_columns = [
        "Current Inventory",
        "Forecast P50 Demand",
        "Forecast P90 Demand",
        "Recommended Order",
        "Projected Shortage",
        "Stockout Risk",
    ]

    for column in numeric_columns:
        if column in rec.columns:
            rec[column] = pd.to_numeric(
                rec[column],
                errors="coerce",
            )

    category_inventory = (
        rec.groupby("Category")
        .agg(
            Current_Inventory=(
                "Current Inventory",
                "sum",
            ),
            Forecast_P50_Demand=(
                "Forecast P50 Demand",
                "sum",
            ),
            Forecast_P90_Demand=(
                "Forecast P90 Demand",
                "sum",
            ),
            Recommended_Order=(
                "Recommended Order",
                "sum",
            ),
            Projected_Shortage=(
                "Projected Shortage",
                "sum",
            ),
            High_Risk=(
                "Risk Level",
                lambda x: int((x == "High").sum()),
            ),
            Medium_Risk=(
                "Risk Level",
                lambda x: int((x == "Medium").sum()),
            ),
            Low_Risk=(
                "Risk Level",
                lambda x: int((x == "Low").sum()),
            ),
            Average_Stockout_Risk=(
                "Stockout Risk",
                "mean",
            ),
        )
        .reset_index()
    )

    result = historical.merge(
        category_inventory,
        on="Category",
        how="left",
    )

    result["Forecast_to_Inventory_Ratio"] = (
        result["Forecast_P50_Demand"]
        / result["Current_Inventory"].replace(
            0,
            np.nan,
        )
    )

    result["Inventory_Coverage_Days"] = (
        result["Current_Inventory"]
        / (
            result["Forecast_P50_Demand"] / 7
        ).replace(
            0,
            np.nan,
        )
    )

    return result.sort_values(
        "Forecast_P50_Demand",
        ascending=False,
    ).reset_index(drop=True)


# ---------------------------------------------------------------------
# Risk analytics
# ---------------------------------------------------------------------

def get_risk_distribution(
    df: Optional[pd.DataFrame] = None,
    recommendations: Optional[pd.DataFrame] = None,
) -> pd.DataFrame:
    """
    Return inventory risk distribution in a consistent format.

    Accepts either the raw sales dataframe or an already generated
    recommendations dataframe. Uses outputs/recommendations_v2.csv
    when the raw sales dataframe is supplied.
    """

    # app.py normally passes the raw sales dataframe.
    if recommendations is None:
        recommendations = df

    # Raw sales data does not contain risk columns, so use the
    # recommendations already generated by Phase 3.
    if recommendations is None:
        recommendations = _load_recommendations()
    elif not any(
        col in recommendations.columns
        for col in ("Risk Level", "Stockout Risk", "Risk Score")
    ):
        generated = _load_recommendations()
        recommendations = generated if not generated.empty else pd.DataFrame()

    if recommendations.empty:
        return pd.DataFrame(
            columns=["Risk Level", "Count"]
        )

    # Current V2 schema.
    if "Risk Level" in recommendations.columns:
        risk_series = recommendations["Risk Level"]

    # Compatibility with older/current variants.
    elif "Stockout Risk" in recommendations.columns:
        risk_score = pd.to_numeric(
            recommendations["Stockout Risk"],
            errors="coerce"
        ).fillna(0)

        risk_series = pd.cut(
            risk_score,
            bins=[-float("inf"), 35, 70, float("inf")],
            labels=["Low", "Medium", "High"]
        )

    elif "Risk Score" in recommendations.columns:
        risk_score = pd.to_numeric(
            recommendations["Risk Score"],
            errors="coerce"
        ).fillna(0)

        risk_series = pd.cut(
            risk_score,
            bins=[-float("inf"), 35, 70, float("inf")],
            labels=["Low", "Medium", "High"]
        )

    elif "Days Until Stockout" in recommendations.columns:
        days = pd.to_numeric(
            recommendations["Days Until Stockout"],
            errors="coerce"
        ).fillna(999)

        risk_series = pd.cut(
            days,
            bins=[-float("inf"), 3, 7, float("inf")],
            labels=["High", "Medium", "Low"]
        )

    else:
        return pd.DataFrame({
            "Risk Level": ["High", "Medium", "Low"],
            "Count": [0, 0, 0]
        })

    return (
        pd.Series(risk_series)
        .value_counts()
        .reindex(["High", "Medium", "Low"], fill_value=0)
        .rename_axis("Risk Level")
        .reset_index(name="Count")
    )


def get_top_risk_products(
    recommendations: Optional[pd.DataFrame] = None,
    n: int = 10,
) -> pd.DataFrame:
    """Return the highest-risk Store×Product recommendations."""

    if recommendations is None:
        recommendations = _load_recommendations()

    if recommendations.empty:
        return pd.DataFrame()

    result = recommendations.copy()

    sort_columns = [
        column
        for column in [
            "Stockout Risk",
            "Days Until Stockout",
            "Projected Shortage",
        ]
        if column in result.columns
    ]

    ascending = [
        False,
        True,
        False,
    ][: len(sort_columns)]

    if sort_columns:
        result = result.sort_values(
            sort_columns,
            ascending=ascending,
        )

    return result.head(n).reset_index(drop=True)


# ---------------------------------------------------------------------
# Model performance
# ---------------------------------------------------------------------

def _recursive_find(
    obj: Any,
    target_keys: set[str],
) -> Dict[str, Any]:
    """Find matching dictionary keys recursively."""

    if isinstance(obj, dict):
        for key, value in obj.items():
            if str(key).lower() in target_keys:
                if isinstance(value, dict):
                    return value
                return {"value": value}

        for value in obj.values():
            found = _recursive_find(
                value,
                target_keys,
            )
            if found:
                return found

    elif isinstance(obj, list):
        for item in obj:
            found = _recursive_find(
                item,
                target_keys,
            )
            if found:
                return found

    return {}


def _read_metadata() -> Dict[str, Any]:
    """Read model metadata safely."""
    if not METADATA_PATH.exists():
        return {}

    try:
        with open(
            METADATA_PATH,
            "r",
            encoding="utf-8",
        ) as file:
            return json.load(file)
    except Exception:
        return {}


def get_model_performance() -> Dict[str, Any]:
    """
    Return model-performance information.

    Supports multiple metadata layouts and falls back to the
    generated validation CSV when necessary.
    """

    metadata = _read_metadata()

    result: Dict[str, Any] = {
        "available": False,
        "metrics": {},
        "baseline_metrics": {},
        "feature_importance": pd.DataFrame(),
        "rolling_validation": pd.DataFrame(),
    }

    # --------------------------------------------------------------
    # Extract metrics from metadata using several possible names.
    # --------------------------------------------------------------

    metrics = _recursive_find(
        metadata,
        {
            "metrics",
            "validation_metrics",
            "holdout_metrics",
            "model_metrics",
        },
    )

    baseline = _recursive_find(
        metadata,
        {
            "baseline_metrics",
            "baseline",
            "benchmark_metrics",
        },
    )

    if metrics:
        if "value" in metrics and isinstance(
            metrics["value"],
            dict,
        ):
            result["metrics"] = metrics["value"]
        else:
            result["metrics"] = metrics

    if baseline:
        if "value" in baseline and isinstance(
            baseline["value"],
            dict,
        ):
            result["baseline_metrics"] = baseline["value"]
        else:
            result["baseline_metrics"] = baseline

    # --------------------------------------------------------------
    # Feature importance.
    # --------------------------------------------------------------

    importance = _recursive_find(
        metadata,
        {
            "feature_importance",
            "feature_importances",
        },
    )

    if importance:
        if "value" in importance:
            importance = importance["value"]

        if isinstance(importance, dict):
            result["feature_importance"] = (
                pd.DataFrame(
                    {
                        "Feature": list(
                            importance.keys()
                        ),
                        "Importance": list(
                            importance.values()
                        ),
                    }
                )
            )

        elif isinstance(importance, list):
            rows = []

            for item in importance:
                if isinstance(item, dict):
                    feature = (
                        item.get("Feature")
                        or item.get("feature")
                        or item.get("name")
                    )

                    value = (
                        item.get("Importance")
                        or item.get("importance")
                        or item.get("value")
                    )

                    if feature is not None:
                        rows.append(
                            {
                                "Feature": feature,
                                "Importance": value,
                            }
                        )

            if rows:
                result["feature_importance"] = (
                    pd.DataFrame(rows)
                )

    # --------------------------------------------------------------
    # Rolling validation CSV fallback.
    # --------------------------------------------------------------

    if ROLLING_VALIDATION_PATH.exists():
        try:
            rolling = pd.read_csv(
                ROLLING_VALIDATION_PATH
            )
            result["rolling_validation"] = rolling

            if not rolling.empty:
                result["available"] = True

                # If metadata metrics are missing, derive the
                # LightGBM V2 aggregate from rolling validation.
                if not result["metrics"]:
                    model_column = None

                    for candidate in [
                        "Model",
                        "model",
                        "Algorithm",
                    ]:
                        if candidate in rolling.columns:
                            model_column = candidate
                            break

                    if model_column:
                        mask = rolling[
                            model_column
                        ].astype(str).str.contains(
                            "LightGBM",
                            case=False,
                            na=False,
                        )

                        model_rows = rolling.loc[
                            mask
                        ]

                        if not model_rows.empty:
                            row = model_rows.iloc[0]

                            result["metrics"] = {
                                key: float(row[key])
                                for key in [
                                    "MAE",
                                    "RMSE",
                                    "MAPE",
                                ]
                                if key in row.index
                            }

        except Exception:
            pass

    # --------------------------------------------------------------
    # Validation prediction fallback.
    # --------------------------------------------------------------

    if VALIDATION_PREDICTIONS_PATH.exists():
        try:
            validation = pd.read_csv(
                VALIDATION_PREDICTIONS_PATH
            )

            actual_col = next(
                (
                    c for c in validation.columns
                    if c.lower()
                    in {
                        "actual demand",
                        "actual_demand",
                        "actual",
                    }
                ),
                None,
            )

            predicted_col = next(
                (
                    c for c in validation.columns
                    if c.lower()
                    in {
                        "predicted demand",
                        "predicted_demand",
                        "prediction",
                        "predicted",
                    }
                ),
                None,
            )

            if (
                actual_col
                and predicted_col
                and not result["metrics"]
            ):
                actual = pd.to_numeric(
                    validation[actual_col],
                    errors="coerce",
                )

                predicted = pd.to_numeric(
                    validation[predicted_col],
                    errors="coerce",
                )

                mask = (
                    actual.notna()
                    & predicted.notna()
                )

                actual = actual[mask]
                predicted = predicted[mask]

                if len(actual):
                    errors = actual - predicted

                    mae = float(
                        errors.abs().mean()
                    )

                    rmse = float(
                        np.sqrt(
                            np.mean(
                                errors ** 2
                            )
                        )
                    )

                    nonzero = actual != 0

                    mape = float(
                        (
                            (
                                errors[nonzero].abs()
                                / actual[nonzero].abs()
                            )
                            .mean()
                            * 100
                        )
                    ) if nonzero.any() else math.nan

                    result["metrics"] = {
                        "MAE": mae,
                        "RMSE": rmse,
                        "MAPE": mape,
                    }

                    result["available"] = True

        except Exception:
            pass

    if result["metrics"]:
        result["available"] = True

    return result


# ---------------------------------------------------------------------
# Monthly analytics
# ---------------------------------------------------------------------

def get_monthly_demand(
    data: Optional[pd.DataFrame] = None,
) -> pd.DataFrame:
    """Return monthly demand trend."""

    df = _ensure_data(data)

    df["Year"] = df["Date"].dt.year
    df["Month"] = df["Date"].dt.month
    df["Month_Name"] = df["Date"].dt.strftime("%b")

    result = (
        df.groupby(
            [
                "Year",
                "Month",
                "Month_Name",
            ],
            as_index=False,
        )
        .agg(
            Demand=("Demand", "sum"),
            Average_Demand=("Demand", "mean"),
        )
        .sort_values(
            ["Year", "Month"]
        )
    )

    return result


# ---------------------------------------------------------------------
# Price / promotion analytics
# ---------------------------------------------------------------------

def get_promotion_analytics(
    data: Optional[pd.DataFrame] = None,
) -> pd.DataFrame:
    """Compare demand with and without promotion."""

    df = _ensure_data(data)

    return (
        df.groupby("Promotion", as_index=False)
        .agg(
            Average_Demand=("Demand", "mean"),
            Total_Demand=("Demand", "sum"),
            Average_Discount=("Discount", "mean"),
            Records=("Demand", "size"),
        )
    )


def get_discount_analytics(
    data: Optional[pd.DataFrame] = None,
) -> pd.DataFrame:
    """Compare demand across discount levels."""

    df = _ensure_data(data)

    return (
        df.groupby("Discount", as_index=False)
        .agg(
            Average_Demand=("Demand", "mean"),
            Total_Demand=("Demand", "sum"),
            Records=("Demand", "size"),
        )
        .sort_values("Discount")
    )


def get_weather_analytics(
    data: Optional[pd.DataFrame] = None,
) -> pd.DataFrame:
    """Compare demand across weather conditions."""

    df = _ensure_data(data)

    return (
        df.groupby(
            "Weather Condition",
            as_index=False,
        )
        .agg(
            Average_Demand=("Demand", "mean"),
            Total_Demand=("Demand", "sum"),
            Records=("Demand", "size"),
        )
        .sort_values(
            "Average_Demand",
            ascending=False,
        )
    )


def get_epidemic_analytics(
    data: Optional[pd.DataFrame] = None,
) -> pd.DataFrame:
    """Compare demand during epidemic vs non-epidemic periods."""

    df = _ensure_data(data)

    return (
        df.groupby(
            "Epidemic",
            as_index=False,
        )
        .agg(
            Average_Demand=("Demand", "mean"),
            Total_Demand=("Demand", "sum"),
            Records=("Demand", "size"),
        )
    )


# ---------------------------------------------------------------------
# Region / seasonality analytics
# ---------------------------------------------------------------------

def get_region_analytics(
    data: Optional[pd.DataFrame] = None,
) -> pd.DataFrame:
    """Return demand analytics by region."""

    df = _ensure_data(data)

    return (
        df.groupby("Region", as_index=False)
        .agg(
            Total_Demand=("Demand", "sum"),
            Average_Demand=("Demand", "mean"),
            Average_Inventory=(
                "Inventory Level",
                "mean",
            ),
            Average_Price=("Price", "mean"),
            Average_Discount=("Discount", "mean"),
        )
        .sort_values(
            "Total_Demand",
            ascending=False,
        )
    )


def get_seasonality_analytics(
    data: Optional[pd.DataFrame] = None,
) -> pd.DataFrame:
    """Return demand analytics by seasonality label."""

    df = _ensure_data(data)

    return (
        df.groupby(
            "Seasonality",
            as_index=False,
        )
        .agg(
            Total_Demand=("Demand", "sum"),
            Average_Demand=("Demand", "mean"),
            Average_Inventory=(
                "Inventory Level",
                "mean",
            ),
        )
        .sort_values(
            "Average_Demand",
            ascending=False,
        )
    )


# ---------------------------------------------------------------------
# Store-product detail
# ---------------------------------------------------------------------

def get_store_product_history(
    store_id: str,
    product_id: str,
    data: Optional[pd.DataFrame] = None,
) -> pd.DataFrame:
    """Return historical observations for one Store×Product."""

    df = _ensure_data(data)

    result = df[
        (df["Store ID"].astype(str) == str(store_id))
        & (
            df["Product ID"].astype(str)
            == str(product_id)
        )
    ].copy()

    return result.sort_values("Date").reset_index(
        drop=True
    )


# ---------------------------------------------------------------------
# Main Phase 4 validation
# ---------------------------------------------------------------------

if __name__ == "__main__":

    print("=" * 70)
    print("PHASE 4 - ANALYTICS V2")
    print("=" * 70)

    data = load_data()
    recommendations = _load_recommendations()

    # Dataset overview
    print("\nDataset Overview")
    print("-" * 70)

    overview = get_dataset_overview(data)

    print(f"Rows: {overview['rows']}")
    print(f"Columns: {overview['columns']}")
    print(
        f"Date range: "
        f"{overview['date_min']} to "
        f"{overview['date_max']}"
    )
    print(f"Stores: {overview['stores']}")
    print(f"Products: {overview['products']}")
    print(f"Categories: {overview['categories']}")
    print(f"Missing values: {overview['missing_values']}")

    # Business summary
    print("\nBusiness Summary")
    print("-" * 70)

    summary = get_business_summary(
        data=data,
        recommendations=recommendations,
    )

    for key, value in summary.items():
        print(f"{key}: {value}")

    # Store analytics
    print("\nStore Analytics")
    print("-" * 70)

    print(
        get_store_analytics(
            data=data,
            recommendations=recommendations,
        ).to_string(index=False)
    )

    # Product analytics
    print("\nTop Products")
    print("-" * 70)

    print(
        get_product_analytics(
            data=data,
            recommendations=recommendations,
        )
        .head(10)
        .to_string(index=False)
    )

    # Category analytics
    print("\nCategory Analytics")
    print("-" * 70)

    category = get_category_analytics(
        data=data,
        recommendations=recommendations,
    )

    print(category.to_string(index=False))

    # Reconciliation checks
    if not recommendations.empty:
        category_inventory = float(
            category["Current_Inventory"].sum()
        )

        category_p50 = float(
            category["Forecast_P50_Demand"].sum()
        )

        category_p90 = float(
            category["Forecast_P90_Demand"].sum()
        )

        category_order = float(
            category["Recommended_Order"].sum()
        )

        print("\nCategory Reconciliation")
        print("-" * 70)
        print(
            f"Current inventory: "
            f"{category_inventory:,.2f} "
            f"/ {summary['total_inventory']:,.2f}"
        )
        print(
            f"P50 forecast: "
            f"{category_p50:,.2f} "
            f"/ {summary['forecast_demand_p50']:,.2f}"
        )
        print(
            f"P90 forecast: "
            f"{category_p90:,.2f} "
            f"/ {summary['forecast_demand_p90']:,.2f}"
        )
        print(
            f"Recommended order: "
            f"{category_order:,.2f} "
            f"/ {summary['recommended_units']:,.2f}"
        )

    # Risk distribution
    print("\nRisk Distribution")
    print("-" * 70)

    print(
        get_risk_distribution(
            recommendations
        ).to_string(index=False)
    )

    # Top risks
    print("\nTop 10 Risks")
    print("-" * 70)

    print(
        get_top_risk_products(
            recommendations,
            n=10,
        ).to_string(index=False)
    )

    # Model performance
    print("\nModel Performance")
    print("-" * 70)

    performance = get_model_performance()

    if performance["available"]:
        print(
            "Model metrics:"
        )
        print(
            performance["metrics"]
        )

        if performance["baseline_metrics"]:
            print(
                "Baseline metrics:"
            )
            print(
                performance["baseline_metrics"]
            )

        if not performance[
            "rolling_validation"
        ].empty:
            print(
                "\nRolling validation:"
            )
            print(
                performance[
                    "rolling_validation"
                ].to_string(index=False)
            )
    else:
        print(
            "Model performance metadata "
            "not available."
        )

    print("\nPhase 4 analytics test complete.")
    print("PHASE 4 PASSED")
