"""
Inventory Optimization V2
-------------------------

Demand Forecast
      ↓
P10 / P50 / P90 Uncertainty
      ↓
Safety Stock
      ↓
Reorder Point
      ↓
Stockout Risk
      ↓
Recommended Order
      ↓
Action Priority

This module uses ONLY sales_data.csv and the forecast outputs
generated by forecasting.py.
"""

from __future__ import annotations

import math
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd

from preprocessing import DATA_PATH, load_data


# ============================================================
# CONFIGURATION
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent

FORECAST_PATH = BASE_DIR / "outputs" / "forecasts_v2.csv"
OUTPUT_PATH = BASE_DIR / "outputs" / "recommendations_v2.csv"

DEFAULT_LEAD_TIME_DAYS = 3
DEFAULT_SERVICE_LEVEL = 0.95
DEFAULT_HORIZON = 7

# Normal-distribution z-value for 95% service level.
SERVICE_LEVEL_Z = 1.645


# ============================================================
# DATA LOADING
# ============================================================

def _load_forecasts(
    horizon: int = DEFAULT_HORIZON,
) -> pd.DataFrame:
    """
    Load V2 forecast output.

    Expected columns:
        Date
        Store ID
        Product ID
        Predicted Demand
        P10 Demand
        P50 Demand
        P90 Demand
    """

    if FORECAST_PATH.exists():
        forecasts = pd.read_csv(FORECAST_PATH)

        forecasts["Date"] = pd.to_datetime(forecasts["Date"])

        # Keep future forecast rows when available.
        if "Forecast Type" in forecasts.columns:
            future = forecasts[
                forecasts["Forecast Type"]
                .astype(str)
                .str.lower()
                .eq("future")
            ].copy()

            if not future.empty:
                forecasts = future

        required = [
            "Date",
            "Store ID",
            "Product ID",
            "Predicted Demand",
        ]

        missing = [c for c in required if c not in forecasts.columns]

        if missing:
            raise ValueError(
                f"Forecast file is missing required columns: {missing}"
            )

        # Backward-compatible fallback.
        if "P50 Demand" not in forecasts.columns:
            forecasts["P50 Demand"] = forecasts["Predicted Demand"]

        if "P10 Demand" not in forecasts.columns:
            forecasts["P10 Demand"] = forecasts["P50 Demand"]

        if "P90 Demand" not in forecasts.columns:
            forecasts["P90 Demand"] = forecasts["P50 Demand"]

        forecasts["P10 Demand"] = pd.to_numeric(
            forecasts["P10 Demand"],
            errors="coerce",
        ).clip(lower=0)

        forecasts["P50 Demand"] = pd.to_numeric(
            forecasts["P50 Demand"],
            errors="coerce",
        ).clip(lower=0)

        forecasts["P90 Demand"] = pd.to_numeric(
            forecasts["P90 Demand"],
            errors="coerce",
        ).clip(lower=0)

        forecasts = forecasts.sort_values(
            ["Store ID", "Product ID", "Date"]
        )

        return forecasts

    # If forecast file does not exist, generate it.
    try:
        from forecasting import forecast_all_products

        forecasts = forecast_all_products(horizon=horizon)

        forecasts["Date"] = pd.to_datetime(forecasts["Date"])

        return forecasts

    except Exception as exc:
        raise FileNotFoundError(
            "V2 forecast output was not found and future forecasts "
            f"could not be generated.\nExpected: {FORECAST_PATH}\n"
            f"Original error: {exc}"
        )


# ============================================================
# BASIC INVENTORY HELPERS
# ============================================================

def get_latest_inventory(
    data: Optional[pd.DataFrame] = None,
) -> pd.DataFrame:
    """
    Get the latest known inventory for every Store × Product pair.
    """

    if data is None:
        data = load_data(DATA_PATH)

    df = data.copy()

    df["Date"] = pd.to_datetime(df["Date"])

    latest = (
        df.sort_values("Date")
        .groupby(
            ["Store ID", "Product ID"],
            as_index=False,
        )
        .tail(1)
    )

    columns = [
        "Store ID",
        "Product ID",
        "Date",
        "Inventory Level",
    ]

    optional_columns = [
        "Category",
        "Region",
        "Price",
        "Discount",
        "Promotion",
    ]

    columns = [
        c for c in columns
        if c in latest.columns
    ]

    columns += [
        c for c in optional_columns
        if c in latest.columns
    ]

    result = latest[columns].copy()

    result = result.rename(
        columns={
            "Date": "Inventory Date",
            "Inventory Level": "Current Inventory",
        }
    )

    result["Current Inventory"] = pd.to_numeric(
        result["Current Inventory"],
        errors="coerce",
    ).fillna(0)

    return result


# ============================================================
# FORECAST AGGREGATION
# ============================================================

def _prepare_forecast_window(
    forecasts: pd.DataFrame,
    horizon: int = DEFAULT_HORIZON,
) -> pd.DataFrame:
    """
    Select the first `horizon` forecast days for every Store × Product.
    """

    df = forecasts.copy()

    df["Date"] = pd.to_datetime(df["Date"])

    df = df.sort_values(
        ["Store ID", "Product ID", "Date"]
    )

    df["forecast_day"] = (
        df.groupby(
            ["Store ID", "Product ID"]
        ).cumcount() + 1
    )

    df = df[df["forecast_day"] <= horizon].copy()

    return df


def _historical_demand_statistics(
    data: pd.DataFrame,
) -> pd.DataFrame:
    """
    Calculate historical demand volatility for every Store × Product.

    This is used as an additional uncertainty signal for safety stock.
    """

    df = data.copy()

    df["Demand"] = pd.to_numeric(
        df["Demand"],
        errors="coerce",
    )

    stats = (
        df.groupby(
            ["Store ID", "Product ID"]
        )["Demand"]
        .agg(
            historical_mean_demand="mean",
            historical_std_demand="std",
            historical_min_demand="min",
            historical_max_demand="max",
        )
        .reset_index()
    )

    stats["historical_std_demand"] = (
        stats["historical_std_demand"]
        .fillna(0)
    )

    return stats


# ============================================================
# STOCKOUT CALCULATIONS
# ============================================================

def _calculate_days_until_stockout(
    inventory: float,
    daily_demand: np.ndarray,
) -> float:
    """
    Calculate when inventory is expected to run out using P50 demand.

    Returns:
        Number of days until stockout.
        np.inf means no stockout within the forecast horizon.
    """

    if inventory <= 0:
        return 0.0

    cumulative = 0.0

    for day, demand in enumerate(daily_demand, start=1):
        cumulative += max(float(demand), 0)

        if cumulative >= inventory:
            previous_cumulative = cumulative - max(
                float(demand),
                0,
            )

            if demand <= 0:
                return float(day)

            remaining = max(
                inventory - previous_cumulative,
                0,
            )

            fraction = remaining / max(float(demand), 1e-9)

            return max(
                day - 1 + fraction,
                0,
            )

    return float("inf")


def calculate_stockout_risk(
    current_inventory: float,
    p10_demand: float,
    p90_demand: float,
) -> float:
    """
    Estimate stockout risk from the forecast uncertainty range.

    Interpretation:

        Inventory <= P10 demand → 100% risk
        Inventory >= P90 demand → 0% risk
        Between P10 and P90 → linear interpolation

    This is an interpretable risk score rather than a fabricated
    probability estimate.
    """

    current_inventory = max(
        float(current_inventory),
        0,
    )

    p10_demand = max(
        float(p10_demand),
        0,
    )

    p90_demand = max(
        float(p90_demand),
        0,
    )

    if p90_demand <= p10_demand:
        if current_inventory < p10_demand:
            return 100.0

        return 0.0

    if current_inventory <= p10_demand:
        return 100.0

    if current_inventory >= p90_demand:
        return 0.0

    risk = (
        (p90_demand - current_inventory)
        / (p90_demand - p10_demand)
    ) * 100

    return float(np.clip(risk, 0, 100))


# ============================================================
# REORDER QUANTITY
# ============================================================

def calculate_reorder_quantity(
    current_inventory: float,
    target_inventory: float,
) -> int:
    """
    Calculate the recommended replenishment quantity.
    """

    quantity = max(
        0,
        target_inventory - current_inventory,
    )

    return int(math.ceil(quantity))


# ============================================================
# RISK CLASSIFICATION
# ============================================================

def _risk_level(
    stockout_risk: float,
    days_until_stockout: float,
    lead_time: int,
) -> str:
    """
    Convert numerical risk into business-friendly categories.
    """

    if (
        stockout_risk >= 70
        or days_until_stockout <= lead_time
    ):
        return "High"

    if (
        stockout_risk >= 35
        or days_until_stockout <= DEFAULT_HORIZON
    ):
        return "Medium"

    return "Low"


def _action_priority(
    risk_level: str,
    days_until_stockout: float,
    lead_time: int,
) -> str:
    """
    Translate risk into an operational action.
    """

    if risk_level == "High":

        if days_until_stockout <= lead_time:
            return "Urgent Replenishment"

        return "Replenish Immediately"

    if risk_level == "Medium":
        return "Replenish Soon"

    return "Monitor"


# ============================================================
# MAIN OPTIMIZATION ENGINE
# ============================================================

def calculate_inventory_recommendations(
    horizon: int = DEFAULT_HORIZON,
    lead_time_days: int = DEFAULT_LEAD_TIME_DAYS,
    service_level: float = DEFAULT_SERVICE_LEVEL,
    data: Optional[pd.DataFrame] = None,
    forecasts: Optional[pd.DataFrame] = None,
) -> pd.DataFrame:
    """
    Generate inventory recommendations for every Store × Product.

    Main outputs:

        Current Inventory
        Forecast Demand P50
        Forecast Demand P90
        Safety Stock
        Reorder Point
        Target Inventory
        Recommended Order
        Projected Shortage
        Days Until Stockout
        Stockout Risk
        Risk Level
        Action Priority
    """

    if data is None:
        data = load_data(DATA_PATH)

    if forecasts is None:
        forecasts = _load_forecasts(horizon)

    forecast_window = _prepare_forecast_window(
        forecasts,
        horizon=horizon,
    )

    inventory = get_latest_inventory(data)

    historical_stats = _historical_demand_statistics(data)

    records = []

    for (
        store_id,
        product_id,
    ), group in forecast_window.groupby(
        ["Store ID", "Product ID"]
    ):

        group = group.sort_values("Date")

        # ----------------------------------------------------
        # Forecast values
        # ----------------------------------------------------

        p10 = group["P10 Demand"].to_numpy(
            dtype=float
        )

        p50 = group["P50 Demand"].to_numpy(
            dtype=float
        )

        p90 = group["P90 Demand"].to_numpy(
            dtype=float
        )

        p10 = np.maximum(p10, 0)
        p50 = np.maximum(p50, 0)
        p90 = np.maximum(p90, p50)

        actual_horizon = len(group)

        if actual_horizon == 0:
            continue

        # ----------------------------------------------------
        # Current inventory
        # ----------------------------------------------------

        inv_match = inventory[
            (inventory["Store ID"] == store_id)
            & (inventory["Product ID"] == product_id)
        ]

        if inv_match.empty:
            current_inventory = 0.0
            inventory_date = None

        else:
            current_inventory = float(
                inv_match.iloc[0]["Current Inventory"]
            )

            inventory_date = inv_match.iloc[0][
                "Inventory Date"
            ]

        # ----------------------------------------------------
        # Historical uncertainty
        # ----------------------------------------------------

        hist_match = historical_stats[
            (historical_stats["Store ID"] == store_id)
            & (historical_stats["Product ID"] == product_id)
        ]

        if hist_match.empty:
            historical_std = 0.0
            historical_mean = float(np.mean(p50))

        else:
            historical_std = float(
                hist_match.iloc[0][
                    "historical_std_demand"
                ]
            )

            historical_mean = float(
                hist_match.iloc[0][
                    "historical_mean_demand"
                ]
            )

        # ----------------------------------------------------
        # Forecast uncertainty
        # ----------------------------------------------------

        interval_width = np.maximum(
            p90 - p10,
            0,
        )

        # Approximate standard deviation from P10-P90
        # interval under a normal-reference interpretation.
        forecast_uncertainty = (
            interval_width / 2.563
        )

        daily_uncertainty = max(
            historical_std,
            float(np.mean(forecast_uncertainty)),
        )

        # ----------------------------------------------------
        # Lead-time demand
        # ----------------------------------------------------

        lead_days = min(
            max(int(lead_time_days), 1),
            actual_horizon,
        )

        lead_time_p10 = float(
            np.sum(p10[:lead_days])
        )

        lead_time_p50 = float(
            np.sum(p50[:lead_days])
        )

        lead_time_p90 = float(
            np.sum(p90[:lead_days])
        )

        # ----------------------------------------------------
        # Safety stock
        # ----------------------------------------------------

        statistical_safety_stock = (
            SERVICE_LEVEL_Z
            * daily_uncertainty
            * math.sqrt(lead_days)
        )

        quantile_safety_stock = max(
            0,
            lead_time_p90 - lead_time_p50,
        )

        safety_stock = max(
            statistical_safety_stock,
            quantile_safety_stock,
        )

        # ----------------------------------------------------
        # Reorder point
        # ----------------------------------------------------

        reorder_point = (
            lead_time_p50
            + safety_stock
        )

        # ----------------------------------------------------
        # Seven-day demand
        # ----------------------------------------------------

        forecast_p10 = float(np.sum(p10))
        forecast_p50 = float(np.sum(p50))
        forecast_p90 = float(np.sum(p90))

        # ----------------------------------------------------
        # Target inventory
        # ----------------------------------------------------

        target_inventory = (
            forecast_p50
            + safety_stock
        )

        # Ensure target covers the conservative forecast
        # when the P90 forecast is materially higher.
        target_inventory = max(
            target_inventory,
            forecast_p90,
        )

        # ----------------------------------------------------
        # Recommended order
        # ----------------------------------------------------

        recommended_order = calculate_reorder_quantity(
            current_inventory,
            target_inventory,
        )

        # ----------------------------------------------------
        # Projected shortage
        # ----------------------------------------------------

        projected_shortage = max(
            0,
            forecast_p90 - current_inventory,
        )

        # ----------------------------------------------------
        # Days until stockout
        # ----------------------------------------------------

        days_until_stockout = (
            _calculate_days_until_stockout(
                current_inventory,
                p50,
            )
        )

        # ----------------------------------------------------
        # Stockout risk
        # ----------------------------------------------------

        stockout_risk = calculate_stockout_risk(
            current_inventory=current_inventory,
            p10_demand=forecast_p10,
            p90_demand=forecast_p90,
        )

        # Additional signal:
        # If stockout occurs within lead time,
        # increase the operational risk to at least 70.
        if days_until_stockout <= lead_days:
            stockout_risk = max(
                stockout_risk,
                70.0,
            )

        stockout_risk = float(
            np.clip(stockout_risk, 0, 100)
        )

        # ----------------------------------------------------
        # Risk level
        # ----------------------------------------------------

        risk_level = _risk_level(
            stockout_risk,
            days_until_stockout,
            lead_days,
        )

        action_priority = _action_priority(
            risk_level,
            days_until_stockout,
            lead_days,
        )

        # ----------------------------------------------------
        # Coverage
        # ----------------------------------------------------

        avg_daily_p50 = (
            forecast_p50 / actual_horizon
        )

        if avg_daily_p50 > 0:
            inventory_coverage_days = (
                current_inventory
                / avg_daily_p50
            )
        else:
            inventory_coverage_days = float("inf")

        # ----------------------------------------------------
        # Store/Product metadata
        # ----------------------------------------------------

        category = None
        region = None

        if not inv_match.empty:

            if "Category" in inv_match.columns:
                category = inv_match.iloc[0]["Category"]

            if "Region" in inv_match.columns:
                region = inv_match.iloc[0]["Region"]

        records.append(
            {
                "Store ID": store_id,
                "Product ID": product_id,
                "Category": category,
                "Region": region,
                "Inventory Date": inventory_date,

                "Current Inventory": round(
                    current_inventory,
                    2,
                ),

                "Forecast P10 Demand": round(
                    forecast_p10,
                    2,
                ),

                "Forecast P50 Demand": round(
                    forecast_p50,
                    2,
                ),

                "Forecast P90 Demand": round(
                    forecast_p90,
                    2,
                ),

                "Lead Time Days": lead_days,

                "Lead Time P50 Demand": round(
                    lead_time_p50,
                    2,
                ),

                "Lead Time P90 Demand": round(
                    lead_time_p90,
                    2,
                ),

                "Safety Stock": int(
                    math.ceil(safety_stock)
                ),

                "Reorder Point": int(
                    math.ceil(reorder_point)
                ),

                "Target Inventory": int(
                    math.ceil(target_inventory)
                ),

                "Recommended Order": recommended_order,

                "Projected Shortage": round(
                    projected_shortage,
                    2,
                ),

                "Days Until Stockout": (
                    round(
                        days_until_stockout,
                        2,
                    )
                    if np.isfinite(
                        days_until_stockout
                    )
                    else np.inf
                ),

                "Inventory Coverage Days": (
                    round(
                        inventory_coverage_days,
                        2,
                    )
                    if np.isfinite(
                        inventory_coverage_days
                    )
                    else np.inf
                ),

                "Stockout Risk": round(
                    stockout_risk,
                    2,
                ),

                "Risk Level": risk_level,

                "Action Priority": action_priority,

                "Historical Avg Daily Demand": round(
                    historical_mean,
                    2,
                ),

                "Historical Daily Std Demand": round(
                    historical_std,
                    2,
                ),

                "Forecast Uncertainty": round(
                    daily_uncertainty,
                    2,
                ),
            }
        )

    result = pd.DataFrame(records)

    if result.empty:
        raise ValueError(
            "No inventory recommendations could be generated."
        )

    # --------------------------------------------------------
    # Priority sorting
    # --------------------------------------------------------

    risk_order = {
        "High": 0,
        "Medium": 1,
        "Low": 2,
    }

    result["_risk_order"] = result[
        "Risk Level"
    ].map(risk_order)

    result = result.sort_values(
        [
            "_risk_order",
            "Stockout Risk",
            "Days Until Stockout",
            "Projected Shortage",
        ],
        ascending=[
            True,
            False,
            True,
            False,
        ],
    )

    result = result.drop(
        columns=["_risk_order"]
    )

    result = result.reset_index(
        drop=True
    )

    return result


# ============================================================
# SUMMARY
# ============================================================

def get_inventory_summary(
    recommendations: Optional[pd.DataFrame] = None,
) -> dict:
    """
    Generate dashboard-level inventory KPIs.
    """

    if recommendations is None:
        recommendations = (
            calculate_inventory_recommendations()
        )

    df = recommendations

    high = int(
        (df["Risk Level"] == "High").sum()
    )

    medium = int(
        (df["Risk Level"] == "Medium").sum()
    )

    low = int(
        (df["Risk Level"] == "Low").sum()
    )

    return {
        "total_inventory": float(
            df["Current Inventory"].sum()
        ),

        "forecast_p50_demand": float(
            df["Forecast P50 Demand"].sum()
        ),

        "forecast_p90_demand": float(
            df["Forecast P90 Demand"].sum()
        ),

        "high_risk": high,

        "medium_risk": medium,

        "low_risk": low,

        "recommended_units": int(
            df["Recommended Order"].sum()
        ),

        "projected_shortage": float(
            df["Projected Shortage"].sum()
        ),

        "stockout_risk_count": int(
            (df["Stockout Risk"] >= 70).sum()
        ),

        "average_stockout_risk": float(
            df["Stockout Risk"].mean()
        ),

        "average_inventory_coverage_days": float(
            df[
                np.isfinite(
                    df["Inventory Coverage Days"]
                )
            ]["Inventory Coverage Days"].mean()
        ),
    }


# ============================================================
# TOP RISKS
# ============================================================

def get_top_risk_products(
    recommendations: Optional[pd.DataFrame] = None,
    n: int = 10,
) -> pd.DataFrame:
    """
    Return the highest-priority inventory risks.
    """

    if recommendations is None:
        recommendations = (
            calculate_inventory_recommendations()
        )

    return (
        recommendations
        .sort_values(
            [
                "Stockout Risk",
                "Projected Shortage",
                "Recommended Order",
            ],
            ascending=[
                False,
                False,
                False,
            ],
        )
        .head(n)
        .copy()
    )


# ============================================================
# STORE ANALYTICS
# ============================================================

def get_store_inventory_analytics(
    recommendations: Optional[pd.DataFrame] = None,
) -> pd.DataFrame:
    """
    Aggregate inventory optimization results by store.
    """

    if recommendations is None:
        recommendations = (
            calculate_inventory_recommendations()
        )

    df = recommendations.copy()

    grouped = (
        df.groupby("Store ID")
        .agg(
            Current_Inventory=(
                "Current Inventory",
                "sum",
            ),

            Forecast_P50_Demand=(
                "Forecast P50 Demand",
                "sum",
            ),

            Forecast_P90_Demand=(
                "Forecast P90 Demand",
                "sum",
            ),

            Recommended_Order=(
                "Recommended Order",
                "sum",
            ),

            Projected_Shortage=(
                "Projected Shortage",
                "sum",
            ),

            High_Risk=(
                "Risk Level",
                lambda x: int(
                    (x == "High").sum()
                ),
            ),

            Medium_Risk=(
                "Risk Level",
                lambda x: int(
                    (x == "Medium").sum()
                ),
            ),

            Low_Risk=(
                "Risk Level",
                lambda x: int(
                    (x == "Low").sum()
                ),
            ),

            Average_Stockout_Risk=(
                "Stockout Risk",
                "mean",
            ),
        )
        .reset_index()
    )

    grouped["Inventory Coverage Days"] = (
        grouped["Current_Inventory"]
        / grouped["Forecast_P50_Demand"]
        * DEFAULT_HORIZON
    ).replace(
        [np.inf, -np.inf],
        np.nan,
    )

    grouped = grouped.sort_values(
        "Average_Stockout_Risk",
        ascending=False,
    )

    return grouped.reset_index(drop=True)


# ============================================================
# PRODUCT ANALYTICS
# ============================================================

def get_product_inventory_analytics(
    recommendations: Optional[pd.DataFrame] = None,
) -> pd.DataFrame:
    """
    Aggregate inventory optimization results by product.
    """

    if recommendations is None:
        recommendations = (
            calculate_inventory_recommendations()
        )

    df = recommendations.copy()

    grouped = (
        df.groupby("Product ID")
        .agg(
            Current_Inventory=(
                "Current Inventory",
                "sum",
            ),

            Forecast_P50_Demand=(
                "Forecast P50 Demand",
                "sum",
            ),

            Forecast_P90_Demand=(
                "Forecast P90 Demand",
                "sum",
            ),

            Recommended_Order=(
                "Recommended Order",
                "sum",
            ),

            Projected_Shortage=(
                "Projected Shortage",
                "sum",
            ),

            High_Risk_Stores=(
                "Risk Level",
                lambda x: int(
                    (x == "High").sum()
                ),
            ),

            Average_Stockout_Risk=(
                "Stockout Risk",
                "mean",
            ),
        )
        .reset_index()
    )

    grouped["Inventory Coverage Days"] = (
        grouped["Current_Inventory"]
        / grouped["Forecast_P50_Demand"]
        * DEFAULT_HORIZON
    ).replace(
        [np.inf, -np.inf],
        np.nan,
    )

    return grouped.sort_values(
        [
            "Average_Stockout_Risk",
            "Projected_Shortage",
        ],
        ascending=[
            False,
            False,
        ],
    ).reset_index(drop=True)


# ============================================================
# DAILY STOCKOUT TIMELINE
# ============================================================

def get_stockout_timeline(
    store_id,
    product_id,
    recommendations: Optional[pd.DataFrame] = None,
    horizon: int = DEFAULT_HORIZON,
    forecasts: Optional[pd.DataFrame] = None,
) -> pd.DataFrame:
    """
    Return a daily inventory projection for a selected
    Store × Product pair.

    Useful for the Inventory Risk and Product Detail pages.
    """

    if recommendations is None:
        recommendations = (
            calculate_inventory_recommendations(
                horizon=horizon
            )
        )

    if forecasts is None:
        forecasts = _load_forecasts(
            horizon=horizon
        )

    rec = recommendations[
        (recommendations["Store ID"] == store_id)
        & (recommendations["Product ID"] == product_id)
    ]

    if rec.empty:
        return pd.DataFrame()

    rec = rec.iloc[0]

    forecast_window = _prepare_forecast_window(
        forecasts,
        horizon=horizon,
    )

    daily = forecast_window[
        (forecast_window["Store ID"] == store_id)
        & (forecast_window["Product ID"] == product_id)
    ].copy()

    if daily.empty:
        return pd.DataFrame()

    daily = daily.sort_values("Date").head(horizon)

    starting_inventory = float(
        rec["Current Inventory"]
    )

    remaining = starting_inventory

    rows = []

    for _, row in daily.iterrows():

        p50 = max(
            float(row["P50 Demand"]),
            0,
        )

        p90 = max(
            float(row["P90 Demand"]),
            p50,
        )

        remaining -= p50

        rows.append(
            {
                "Date": row["Date"],
                "Store ID": store_id,
                "Product ID": product_id,
                "P50 Demand": round(p50, 2),
                "P90 Demand": round(p90, 2),
                "Projected Inventory": round(
                    max(remaining, 0),
                    2,
                ),
                "Reorder Point": rec[
                    "Reorder Point"
                ],
                "Stockout": remaining <= 0,
            }
        )

    return pd.DataFrame(rows)


# ============================================================
# SAVE OUTPUT
# ============================================================

def save_inventory_recommendations(
    recommendations: Optional[pd.DataFrame] = None,
) -> Path:
    """
    Save recommendations to outputs/recommendations_v2.csv.
    """

    if recommendations is None:
        recommendations = (
            calculate_inventory_recommendations()
        )

    OUTPUT_PATH.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    recommendations.to_csv(
        OUTPUT_PATH,
        index=False,
    )

    return OUTPUT_PATH


# ============================================================
# BACKWARD-COMPATIBLE ALIAS
# ============================================================

def build_inventory_recommendations(
    *args,
    **kwargs,
) -> pd.DataFrame:
    """
    Compatibility wrapper for older app/analytics code.
    """

    return calculate_inventory_recommendations(
        *args,
        **kwargs,
    )


# ============================================================
# MAIN TEST
# ============================================================

if __name__ == "__main__":

    print("=" * 70)
    print("PHASE 3 - INVENTORY OPTIMIZATION V2")
    print("=" * 70)

    recommendations = (
        calculate_inventory_recommendations()
    )

    summary = get_inventory_summary(
        recommendations
    )

    print("\nInventory Optimization Summary")
    print("-" * 70)

    for key, value in summary.items():
        print(f"{key}: {value}")

    print("\nTop Inventory Risks")
    print("-" * 70)

    display_columns = [
        "Store ID",
        "Product ID",
        "Current Inventory",
        "Forecast P50 Demand",
        "Forecast P90 Demand",
        "Safety Stock",
        "Reorder Point",
        "Recommended Order",
        "Projected Shortage",
        "Days Until Stockout",
        "Stockout Risk",
        "Risk Level",
        "Action Priority",
    ]

    print(
        get_top_risk_products(
            recommendations,
            n=10,
        )[display_columns].to_string(
            index=False
        )
    )

    output_file = save_inventory_recommendations(
        recommendations
    )

    print("\nSaved:")
    print(output_file)

    print("\nStore Analytics")
    print("-" * 70)

    print(
        get_store_inventory_analytics(
            recommendations
        ).to_string(index=False)
    )

    print("\nProduct Analytics")
    print("-" * 70)

    print(
        get_product_inventory_analytics(
            recommendations
        ).head(10).to_string(index=False)
    )

    print("\nPHASE 3 PASSED")